const types = {
  AUTH_FETCH: "AUTH/fetch",
  AUTH_SUCCESS: "AUTH/success",
  AUTH_ERROR: "AUTH/error",

  USER_LOGIN_FETCH: "USER_LOGIN/fetch",
  USER_LOGIN_SUCCESS: "USER_LOGIN/success",
  USER_LOGIN_ERROR: "USER_LOGIN/error",

  USER_LOGOUT_FETCH: "USER_LOGOUT/fetch",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT/success",
  USER_LOGOUT_ERROR: "USER_LOGOUT/error",

  APPLICATIONS_FETCH: "APPLICATIONS/fetch",
  APPLICATIONS_DATA: "APPLICATIONS/data",
  APPLICATIONS_ERROR: "APPLICATIONS/error",

  USER_APPLICATIONS_FETCH: "USER_APPLICATIONS/fetch",
  USER_APPLICATIONS_DATA: "USER_APPLICATIONS/data",
  USER_APPLICATIONS_ERROR: "USER_APPLICATIONS/error",

  SELECTED_USER_APPLICATIONS_FETCH: "SELECTED_USER_APPLICATIONS/fetch",
  SELECTED_USER_APPLICATIONS_DATA: "SELECTED_USER_APPLICATIONS/data",
  SELECTED_USER_APPLICATIONS_ERROR: "SELECTED_USER_APPLICATIONS/error",
  SELECTED_USER_APPLICATIONS_RESET: "SELECTED_USER_APPLICATIONS/reset",

  APPLICATION_MENU_FETCH: "APPLICATION_MENU/fetch",
  APPLICATION_MENU_DATA: "APPLICATION_MENU/data",
  APPLICATION_MENU_ERROR: "APPLICATION_MENU/error",
  APPLICATION_MENU_RESET: "APPLICATION_MENU/reset",

  USER_APPLICATION_MENU_FETCH: "USER_APPLICATION_MENU/fetch",
  USER_APPLICATION_MENU_DATA: "USER_APPLICATION_MENU/data",
  USER_APPLICATION_MENU_ERROR: "USER_APPLICATION_MENU/error",
  USER_APPLICATION_MENU_RESET: "USER_APPLICATION_MENU/reset",

  USER_APPLICATION_ROLE_FETCH: "USER_APPLICATION_ROLE/fetch",
  USER_APPLICATION_ROLE_DATA: "USER_APPLICATION_ROLE/data",
  USER_APPLICATION_ROLE_ERROR: "USER_APPLICATION_ROLE/error",
  USER_APPLICATION_ROLE_RESET: "USER_APPLICATION_ROLE/reset",

  USER_PROFILE_FETCH: "USER_PROFILE/fetch",
  USER_PROFILE_DATA: "USER_PROFILE/data",
  USER_PROFILE_ERROR: "USER_PROFILE/error",
  USER_PROFILE_RESET: "USER_PROFILE/reset",

  USERS_FETCH: "USERS/fetch",
  USERS_DATA: "USERS/data",
  USERS_ERROR: "USERS/error",

  USER_DETAIL_FETCH: "USER_DETAIL/fetch",
  USER_DETAIL_DATA: "USER_DETAIL/data",
  USER_DETAIL_ERROR: "USER_DETAIL/error",

  ADD_USER_FETCH: "ADD_USER/fetch",
  ADD_USER_SUCCESS: "ADD_USER/SUCCESS",
  ADD_USER_ERROR: "ADD_USER/error",

  UPDATE_USER_FETCH: "UPDATE_USER/fetch",
  UPDATE_USER_SUCCESS: "UPDATE_USER/SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER/error",

  NCR_ALL_RECORDS_FETCH: "NCR_ALL_RECORDS/fetch",
  NCR_ALL_RECORDS_DATA: "NCR_ALL_RECORDS/data",
  NCR_ALL_RECORDS_ERROR: "NCR_ALL_RECORDS/error",
  NCR_ALL_RECORDS_RESET: "NCR_ALL_RECORDS/reset",

  NCR_RECORD_FETCH: "NCR_RECORD/fetch",
  NCR_RECORD_DATA: "NCR_RECORD/data",
  NCR_RECORD_ERROR: "NCR_RECORD/error",
  NCR_RECORD_RESET: "NCR_RECORD/reset",

  NCR_RECORD_DETAIL_FETCH: "NCR_RECORD_DETAIL/fetch",
  NCR_RECORD_DETAIL_DATA: "NCR_RECORD_DETAIL/data",
  NCR_RECORD_DETAIL_ERROR: "NCR_RECORD_DETAIL/error",
  NCR_RECORD_DETAIL_RESET: "NCR_RECORD_DETAIL/reset",

  ROLES_FETCH: "ROLES/fetch",
  ROLES_DATA: "ROLES/data",
  ROLES_ERROR: "ROLES/error",

  EMPLOYEES_FETCH: "EMPLOYEES/fetch",
  EMPLOYEES_DATA: "EMPLOYEES/data",
  EMPLOYEES_ERROR: "EMPLOYEES/error",

  CATEGORIES_FETCH: "CATEGORIES/fetch",
  CATEGORIES_DATA: "CATEGORIES/data",
  CATEGORIES_ERROR: "CATEGORIES/error",

  COMPANIES_FETCH: "COMPANIES/fetch",
  COMPANIES_DATA: "COMPANIES/data",
  COMPANIES_ERROR: "COMPANIES/error",

  USER_COMPANIES_FETCH: "USER_COMPANIES/fetch",
  USER_COMPANIES_DATA: "USER_COMPANIES/data",
  USER_COMPANIES_ERROR: "USER_COMPANIES/error",

  DEPARTMENTS_FETCH: "DEPARTMENTS/fetch",
  DEPARTMENTS_DATA: "DEPARTMENTS/data",
  DEPARTMENTS_ERROR: "DEPARTMENTS/error",

  AREAS_FETCH: "AREAS/fetch",
  AREAS_DATA: "AREAS/data",
  AREAS_ERROR: "AREAS/error",

  SOURCES_FETCH: "SOURCES/fetch",
  SOURCES_DATA: "SOURCES/data",
  SOURCES_ERROR: "SOURCES/error",

  NC_TYPES_FETCH: "NC_TYPES/fetch",
  NC_TYPES_DATA: "NC_TYPES/data",
  NC_TYPES_ERROR: "NC_TYPES/error",

  MANAGEMENT_SYSTEMS_FETCH: "MANAGEMENT_SYSTEMS/fetch",
  MANAGEMENT_SYSTEMS_DATA: "MANAGEMENT_SYSTEMS/data",
  MANAGEMENT_SYSTEMS_ERROR: "MANAGEMENT_SYSTEMS/error",

  STATUSES_FETCH: "STATUSES/fetch",
  STATUSES_DATA: "STATUSES/data",
  STATUSES_ERROR: "STATUSES/error",

  MONTHS_FETCH: "MONTHS/fetch",
  MONTHS_DATA: "MONTHS/data",
  MONTHS_ERROR: "MONTHS/error",

  AUDIT_FINDINGS_FETCH: "AUDIT_FINDINGS/fetch",
  AUDIT_FINDINGS_DATA: "AUDIT_FINDINGS/data",
  AUDIT_FINDINGS_ERROR: "AUDIT_FINDINGS/error",

  NCR_ADD_RECORD_FETCH: "NCR_ADD_RECORD/fetch",
  NCR_ADD_RECORD_SUCCESS: "NCR_ADD_RECORD/success",
  NCR_ADD_RECORD_ERROR: "NCR_ADD_RECORD/error",

  NCR_UPDATE_RECORD_FETCH: "NCR_UPDATE_RECORD/fetch",
  NCR_UPDATE_RECORD_SUCCESS: "NCR_UPDATE_RECORD/success",
  NCR_UPDATE_RECORD_ERROR: "NCR_UPDATE_RECORD/error",

  UPDATE_CLOSED_OUT_DATE_FETCH: "UPDATE_CLOSED_OUT_DATE/fetch",
  UPDATE_CLOSED_OUT_DATE_SUCCESS: "UPDATE_CLOSED_OUT_DATE/success",
  UPDATE_CLOSED_OUT_DATE_ERROR: "UPDATE_CLOSED_OUT_DATE/error",

  UPDATE_REMARKS_FETCH: "UPDATE_REMARKS/fetch",
  UPDATE_REMARKS_SUCCESS: "UPDATE_REMARKS/success",
  UPDATE_REMARKS_ERROR: "UPDATE_REMARKS/error",

  NCR_BY_MONTH_FETCH: "NCR_BY_MONTH/fetch",
  NCR_BY_MONTH_DATA: "NCR_BY_MONTH/data",
  NCR_BY_MONTH_ERROR: "NCR_BY_MONTH/error",

  NCR_BY_DEPARTMENT_FETCH: "NCR_BY_DEPARTMENT/fetch",
  NCR_BY_DEPARTMENT_DATA: "NCR_BY_DEPARTMENT/data",
  NCR_BY_DEPARTMENT_ERROR: "NCR_BY_DEPARTMENT/error",

  NCR_BY_STATUS_FETCH: "NCR_BY_STATUS/fetch",
  NCR_BY_STATUS_DATA: "NCR_BY_STATUS/data",
  NCR_BY_STATUS_ERROR: "NCR_BY_STATUS/error",

  NCR_BY_STATUS_AND_MONTH_FETCH: "NCR_BY_STATUS_AND_MONTH/fetch",
  NCR_BY_STATUS_AND_MONTH_DATA: "NCR_BY_STATUS_AND_MONTH/data",
  NCR_BY_STATUS_AND_MONTH_ERROR: "NCR_BY_STATUS_AND_MONTH/error",

  NCR_BY_COMPANY_FETCH: "NCR_BY_COMPANY/fetch",
  NCR_BY_COMPANY_DATA: "NCR_BY_COMPANY/data",
  NCR_BY_COMPANY_ERROR: "NCR_BY_COMPANY/error",

  CALIBRATION_RECORD_FETCH: "CALIBRATION_RECORD/fetch",
  CALIBRATION_RECORD_DATA: "CALIBRATION_RECORD/data",
  CALIBRATION_RECORD_ERROR: "CALIBRATION_RECORD/error",
  CALIBRATION_RECORD_RESET: "CALIBRATION_RECORD/reset",

  CALIBRATION_RECORD_DETAIL_FETCH: "CALIBRATION_RECORD_DETAIL/fetch",
  CALIBRATION_RECORD_DETAIL_DATA: "CALIBRATION_RECORD_DETAIL/data",
  CALIBRATION_RECORD_DETAIL_ERROR: "CALIBRATION_RECORD_DETAIL/error",
  CALIBRATION_RECORD_DETAIL_RESET: "CALIBRATION_RECORD_DETAIL/reset",

  FREQUENCIES_FETCH: "FREQUENCIES/fetch",
  FREQUENCIES_DATA: "FREQUENCIES/data",
  FREQUENCIES_ERROR: "FREQUENCIES/error",

  CALIBRATION_ADD_RECORD_FETCH: "CALIBRATION_ADD_RECORD/fetch",
  CALIBRATION_ADD_RECORD_SUCCESS: "CALIBRATION_ADD_RECORD/success",
  CALIBRATION_ADD_RECORD_ERROR: "CALIBRATION_ADD_RECORD/error",

  CALIBRATION_UPDATE_RECORD_FETCH: "CALIBRATION_UPDATE_RECORD/fetch",
  CALIBRATION_UPDATE_RECORD_SUCCESS: "CALIBRATION_UPDATE_RECORD/success",
  CALIBRATION_UPDATE_RECORD_ERROR: "CALIBRATION_UPDATE_RECORD/error",

  DUE_CALIBRATION_BY_MONTH_FETCH: "DUE_CALIBRATION_BY_MONTH/fetch",
  DUE_CALIBRATION_BY_MONTH_DATA: "DUE_CALIBRATION_BY_MONTH/data",
  DUE_CALIBRATION_BY_MONTH_ERROR: "DUE_CALIBRATION_BY_MONTH/error",

  CALIBRATION_BY_FREQUENCY_FETCH: "CALIBRATION_BY_FREQUENCY/fetch",
  CALIBRATION_BY_FREQUENCY_DATA: "CALIBRATION_BY_FREQUENCY/data",
  CALIBRATION_BY_FREQUENCY_ERROR: "CALIBRATION_BY_FREQUENCY/error",

  CALIBRATION_ALL_RECORDS_FETCH: "CALIBRATION_ALL_RECORDS/fetch",
  CALIBRATION_ALL_RECORDS_DATA: "CALIBRATION_ALL_RECORDS/data",
  CALIBRATION_ALL_RECORDS_ERROR: "CALIBRATION_ALL_RECORDS/error",
  CALIBRATION_ALL_RECORDS_RESET: "CALIBRATION_ALL_RECORDS/reset",

  YEARS_FETCH: "YEARS/fetch",
  YEARS_DATA: "YEARS/data",
  YEARS_ERROR: "YEARS/error",

  QUATERS_FETCH: "QUATERS/fetch",
  QUATERS_DATA: "QUATERS/data",
  QUATERS_ERROR: "QUATERS/error",

  ASPECTS_FETCH: "ASPECTS/fetch",
  ASPECTS_DATA: "ASPECTS/data",
  ASPECTS_ERROR: "ASPECTS/error",

  SURVEYS_FETCH: "SURVEYS/fetch",
  SURVEYS_DATA: "SURVEYS/data",
  SURVEYS_ERROR: "SURVEYS/error",
  SURVEYS_RESET: "SURVEYS/reset",

  SURVEY_DETAIL_FETCH: "SURVEY_DETAIL/fetch",
  SURVEY_DETAIL_DATA: "SURVEY_DETAIL/data",
  SURVEY_DETAIL_ERROR: "SURVEY_DETAIL/error",
  SURVEY_DETAIL_RESET: "SURVEY_DETAIL/reset",

  ADD_SURVEY_FETCH: "ADD_SURVEY/fetch",
  ADD_SURVEY_SUCCESS: "ADD_SURVEY/success",
  ADD_SURVEY_ERROR: "ADD_SURVEY/error",

  UPDATE_SURVEY_FETCH: "UPDATE_SURVEY/fetch",
  UPDATE_SURVEY_SUCCESS: "UPDATE_SURVEY/success",
  UPDATE_SURVEY_ERROR: "UPDATE_SURVEY/error",

  ADD_SURVEY_FEEDBACK_FETCH: "ADD_SURVEY_FEEDBACK/fetch",
  ADD_SURVEY_FEEDBACK_SUCCESS: "ADD_SURVEY_FEEDBACK/success",
  ADD_SURVEY_FEEDBACK_ERROR: "ADD_SURVEY_FEEDBACK/error",

  SEND_SURVEY_REMINDER_FETCH: "SEND_SURVEY_REMINDER/fetch",
  SEND_SURVEY_REMINDER_SUCCESS: "SEND_SURVEY_REMINDER/success",
  SEND_SURVEY_REMINDER_ERROR: "SEND_SURVEY_REMINDER/error",

  SURVEY_RATING_BY_ASPECT_YEAR_FETCH: "SURVEY_RATING_BY_ASPECT_YEAR/fetch",
  SURVEY_RATING_BY_ASPECT_YEAR_DATA: "SURVEY_RATING_BY_ASPECT_YEAR/data",
  SURVEY_RATING_BY_ASPECT_YEAR_ERROR: "SURVEY_RATING_BY_ASPECT_YEAR/error",
  SURVEY_RATING_BY_ASPECT_YEAR_RESET: "SURVEY_RATING_BY_ASPECT_YEAR/reset",

  SURVEY_RATING_BY_COMPANY_YEAR_FETCH: "SURVEY_RATING_BY_COMPANY_YEAR/fetch",
  SURVEY_RATING_BY_COMPANY_YEAR_DATA: "SURVEY_RATING_BY_COMPANY_YEAR/data",
  SURVEY_RATING_BY_COMPANY_YEAR_ERROR: "SURVEY_RATING_BY_COMPANY_YEAR/error",
  SURVEY_RATING_BY_COMPANY_YEAR_RESET: "SURVEY_RATING_BY_COMPANY_YEAR/reset",

  ALL_SURVEYS_DATA_FETCH: "ALL_SURVEYS_DATA/fetch",
  ALL_SURVEYS_DATA_DATA: "ALL_SURVEYS_DATA/data",
  ALL_SURVEYS_DATA_ERROR: "ALL_SURVEYS_DATA/error",
  ALL_SURVEYS_DATA_RESET: "ALL_SURVEYS_DATA/reset",

  AUDIT_STATUSES_FETCH: "AUDIT_STATUSES/fetch",
  AUDIT_STATUSES_DATA: "AUDIT_STATUSES/data",
  AUDIT_STATUSES_ERROR: "AUDIT_STATUSES/error",
  AUDIT_STATUSES_RESET: "AUDIT_STATUSES/reset",

  AUDITS_FETCH: "AUDITS/fetch",
  AUDITS_DATA: "AUDITS/data",
  AUDITS_ERROR: "AUDITS/error",
  AUDITS_RESET: "AUDITS/reset",

  AUDIT_DETAIL_FETCH: "AUDIT_DETAIL/fetch",
  AUDIT_DETAIL_DATA: "AUDIT_DETAIL/data",
  AUDIT_DETAIL_ERROR: "AUDIT_DETAIL/error",
  AUDIT_DETAIL_RESET: "AUDIT_DETAIL/reset",

  ADD_AUDIT_FETCH: "ADD_AUDIT/fetch",
  ADD_AUDIT_SUCCESS: "ADD_AUDIT/success",
  ADD_AUDIT_ERROR: "ADD_AUDIT/error",

  UPDATE_AUDIT_FETCH: "UPDATE_AUDIT/fetch",
  UPDATE_AUDIT_SUCCESS: "UPDATE_AUDIT/success",
  UPDATE_AUDIT_ERROR: "UPDATE_AUDIT/error",

  ADD_AUDIT_NOTIFICATION_FETCH: "ADD_AUDIT_NOTIFICATION/fetch",
  ADD_AUDIT_NOTIFICATION_SUCCESS: "ADD_AUDIT_NOTIFICATION/success",
  ADD_AUDIT_NOTIFICATION_ERROR: "ADD_AUDIT_NOTIFICATION/error",

  ADD_AUDIT_CHECKLIST_FETCH: "ADD_AUDIT_CHECKLIST/fetch",
  ADD_AUDIT_CHECKLIST_SUCCESS: "ADD_AUDIT_CHECKLIST/success",
  ADD_AUDIT_CHECKLIST_ERROR: "ADD_AUDIT_CHECKLIST/error",

  UPDATE_AUDIT_CHECKLIST_FETCH: "UPDATE_AUDIT_CHECKLIST/fetch",
  UPDATE_AUDIT_CHECKLIST_SUCCESS: "UPDATE_AUDIT_CHECKLIST/success",
  UPDATE_AUDIT_CHECKLIST_ERROR: "UPDATE_AUDIT_CHECKLIST/error",

  DELETE_AUDIT_CHECKLIST_FETCH: "DELETE_AUDIT_CHECKLIST/fetch",
  DELETE_AUDIT_CHECKLIST_SUCCESS: "DELETE_AUDIT_CHECKLIST/success",
  DELETE_AUDIT_CHECKLIST_ERROR: "DELETE_AUDIT_CHECKLIST/error",

  FINDING_TYPES_FETCH: "FINDING_TYPES/fetch",
  FINDING_TYPES_DATA: "FINDING_TYPES/data",
  FINDING_TYPES_ERROR: "FINDING_TYPES/error",
  FINDING_TYPES_RESET: "FINDING_TYPES/reset",

  LOCATIONS_FETCH: "LOCATIONS/fetch",
  LOCATIONS_DATA: "LOCATIONS/data",
  LOCATIONS_ERROR: "LOCATIONS/error",
  LOCATIONS_RESET: "LOCATIONS/reset",

  ADD_LOCATION_FETCH: "ADD_LOCATION/fetch",
  ADD_LOCATION_SUCCESS: "ADD_LOCATION/success",
  ADD_LOCATION_ERROR: "ADD_LOCATION/error",

  EMERGENCY_DRILL_TYPES_FETCH: "EMERGENCY_DRILL_TYPES/fetch",
  EMERGENCY_DRILL_TYPES_DATA: "EMERGENCY_DRILL_TYPES/data",
  EMERGENCY_DRILL_TYPES_ERROR: "EMERGENCY_DRILL_TYPES/error",
  EMERGENCY_DRILL_TYPES_RESET: "EMERGENCY_DRILL_TYPES/reset",

  EMERGENCY_DRILLS_FETCH: "EMERGENCY_DRILLS/fetch",
  EMERGENCY_DRILLS_DATA: "EMERGENCY_DRILLS/data",
  EMERGENCY_DRILLS_ERROR: "EMERGENCY_DRILLS/error",
  EMERGENCY_DRILLS_RESET: "EMERGENCY_DRILLS/reset",

  EMERGENCY_DRILL_DETAIL_FETCH: "EMERGENCY_DRILL_DETAIL/fetch",
  EMERGENCY_DRILL_DETAIL_DATA: "EMERGENCY_DRILL_DETAIL/data",
  EMERGENCY_DRILL_DETAIL_ERROR: "EMERGENCY_DRILL_DETAIL/error",
  EMERGENCY_DRILL_DETAIL_RESET: "EMERGENCY_DRILL_DETAIL/reset",

  ADD_EMERGENCY_DRILL_FETCH: "ADD_EMERGENCY_DRILL/fetch",
  ADD_EMERGENCY_DRILL_SUCCESS: "ADD_EMERGENCY_DRILL/success",
  ADD_EMERGENCY_DRILL_ERROR: "ADD_EMERGENCY_DRILL/error",

  UPDATE_EMERGENCY_DRILL_FETCH: "UPDATE_EMERGENCY_DRILL/fetch",
  UPDATE_EMERGENCY_DRILL_SUCCESS: "UPDATE_EMERGENCY_DRILL/success",
  UPDATE_EMERGENCY_DRILL_ERROR: "UPDATE_EMERGENCY_DRILL/error",

  ADD_EMERGENCY_DRILL_NOTIFICATION_FETCH:
    "ADD_EMERGENCY_DRILL_NOTIFICATION/fetch",
  ADD_EMERGENCY_DRILL_NOTIFICATION_SUCCESS:
    "ADD_EMERGENCY_DRILL_NOTIFICATION/success",
  ADD_EMERGENCY_DRILL_NOTIFICATION_ERROR:
    "ADD_EMERGENCY_DRILL_NOTIFICATION/error",

  DRILL_ATTENDENCE_EMPLOYEES_FETCH: "DRILL_ATTENDENCE_EMPLOYEES/fetch",
  DRILL_ATTENDENCE_EMPLOYEES_DATA: "DRILL_ATTENDENCE_EMPLOYEES/data",
  DRILL_ATTENDENCE_EMPLOYEES_ERROR: "DRILL_ATTENDENCE_EMPLOYEES/error",
  DRILL_ATTENDENCE_EMPLOYEES_RESET: "DRILL_ATTENDENCE_EMPLOYEES/reset",

  SAVE_EMPLOYEE_ATTENDENCE_FETCH: "SAVE_EMPLOYEE_ATTENDENCE/fetch",
  SAVE_EMPLOYEE_ATTENDENCE_SUCCESS: "SAVE_EMPLOYEE_ATTENDENCE/success",
  SAVE_EMPLOYEE_ATTENDENCE_ERROR: "SAVE_EMPLOYEE_ATTENDENCE/error",

  ENVIRONMENTAL_PROBABILITYS_FETCH: "ENVIRONMENTAL_PROBABILITYS/fetch",
  ENVIRONMENTAL_PROBABILITYS_DATA: "ENVIRONMENTAL_PROBABILITYS/data",
  ENVIRONMENTAL_PROBABILITYS_ERROR: "ENVIRONMENTAL_PROBABILITYS/error",
  ENVIRONMENTAL_PROBABILITYS_RESET: "ENVIRONMENTAL_PROBABILITYS/reset",

  ENVIRONMENTAL_SEVERITYS_FETCH: "ENVIRONMENTAL_SEVERITYS/fetch",
  ENVIRONMENTAL_SEVERITYS_DATA: "ENVIRONMENTAL_SEVERITYS/data",
  ENVIRONMENTAL_SEVERITYS_ERROR: "ENVIRONMENTAL_SEVERITYS/error",
  ENVIRONMENTAL_SEVERITYS_RESET: "ENVIRONMENTAL_SEVERITYS/reset",

  ENVIRONMENTAL_ACTIVITIES_FETCH: "ENVIRONMENTAL_ACTIVITIES/fetch",
  ENVIRONMENTAL_ACTIVITIES_DATA: "ENVIRONMENTAL_ACTIVITIES/data",
  ENVIRONMENTAL_ACTIVITIES_ERROR: "ENVIRONMENTAL_ACTIVITIES/error",
  ENVIRONMENTAL_ACTIVITIES_RESET: "ENVIRONMENTAL_ACTIVITIES/reset",

  ADD_ENVIRONMENTAL_ACTIVITY_FETCH: "ADD_ENVIRONMENTAL_ACTIVITY/fetch",
  ADD_ENVIRONMENTAL_ACTIVITY_SUCCESS: "ADD_ENVIRONMENTAL_ACTIVITY/success",
  ADD_ENVIRONMENTAL_ACTIVITY_ERROR: "ADD_ENVIRONMENTAL_ACTIVITY/error",

  ENVIRONMENTAL_RECORDS_FETCH: "ENVIRONMENTAL_RECORDS/fetch",
  ENVIRONMENTAL_RECORDS_DATA: "ENVIRONMENTAL_RECORDS/data",
  ENVIRONMENTAL_RECORDS_ERROR: "ENVIRONMENTAL_RECORDS/error",
  ENVIRONMENTAL_RECORDS_RESET: "ENVIRONMENTAL_RECORDS/reset",

  ENVIRONMENTAL_RECORD_DETAIL_FETCH: "ENVIRONMENTAL_RECORD_DETAIL/fetch",
  ENVIRONMENTAL_RECORD_DETAIL_DATA: "ENVIRONMENTAL_RECORD_DETAIL/data",
  ENVIRONMENTAL_RECORD_DETAIL_ERROR: "ENVIRONMENTAL_RECORD_DETAIL/error",
  ENVIRONMENTAL_RECORD_DETAIL_RESET: "ENVIRONMENTAL_RECORD_DETAIL/reset",

  ADD_ENVIRONMENTAL_RECORD_FETCH: "ADD_ENVIRONMENTAL_RECORD/fetch",
  ADD_ENVIRONMENTAL_RECORD_SUCCESS: "ADD_ENVIRONMENTAL_RECORD/success",
  ADD_ENVIRONMENTAL_RECORD_ERROR: "ADD_ENVIRONMENTAL_RECORD/error",

  UPDATE_ENVIRONMENTAL_RECORD_FETCH: "UPDATE_ENVIRONMENTAL_RECORD/fetch",
  UPDATE_ENVIRONMENTAL_RECORD_SUCCESS: "UPDATE_ENVIRONMENTAL_RECORD/success",
  UPDATE_ENVIRONMENTAL_RECORD_ERROR: "UPDATE_ENVIRONMENTAL_RECORD/error",

  FACE_TERMINALS_FETCH: "FACE_TERMINALS/fetch",
  FACE_TERMINALS_DATA: "FACE_TERMINALS/data",
  FACE_TERMINALS_ERROR: "FACE_TERMINALS/error",
  FACE_TERMINALS_RESET: "FACE_TERMINALS/reset",

  HIRA_PROBABILITYS_FETCH: "HIRA_PROBABILITYS/fetch",
  HIRA_PROBABILITYS_DATA: "HIRA_PROBABILITYS/data",
  HIRA_PROBABILITYS_ERROR: "HIRA_PROBABILITYS/error",
  HIRA_PROBABILITYS_RESET: "HIRA_PROBABILITYS/reset",

  HIRA_SEVERITYS_FETCH: "HIRA_SEVERITYS/fetch",
  HIRA_SEVERITYS_DATA: "HIRA_SEVERITYS/data",
  HIRA_SEVERITYS_ERROR: "HIRA_SEVERITYS/error",
  HIRA_SEVERITYS_RESET: "HIRA_SEVERITYS/reset",

  HIRA_ENTITIES_FETCH: "HIRA_ENTITIES/fetch",
  HIRA_ENTITIES_DATA: "HIRA_ENTITIES/data",
  HIRA_ENTITIES_ERROR: "HIRA_ENTITIES/error",
  HIRA_ENTITIES_RESET: "HIRA_ENTITIES/reset",

  HIRA_HAZARDS_FETCH: "HIRA_HAZARDS/fetch",
  HIRA_HAZARDS_DATA: "HIRA_HAZARDS/data",
  HIRA_HAZARDS_ERROR: "HIRA_HAZARDS/error",
  HIRA_HAZARDS_RESET: "HIRA_HAZARDS/reset",

  ADD_HIRA_HAZARD_FETCH: "ADD_HIRA_HAZARD/fetch",
  ADD_HIRA_HAZARD_SUCCESS: "ADD_HIRA_HAZARD/success",
  ADD_HIRA_HAZARD_ERROR: "ADD_HIRA_HAZARD/error",

  HIRA_RECORDS_FETCH: "HIRA_RECORDS/fetch",
  HIRA_RECORDS_DATA: "HIRA_RECORDS/data",
  HIRA_RECORDS_ERROR: "HIRA_RECORDS/error",
  HIRA_RECORDS_RESET: "HIRA_RECORDS/reset",

  HIRA_RECORD_DETAIL_FETCH: "HIRA_RECORD_DETAIL/fetch",
  HIRA_RECORD_DETAIL_DATA: "HIRA_RECORD_DETAIL/data",
  HIRA_RECORD_DETAIL_ERROR: "HIRA_RECORD_DETAIL/error",
  HIRA_RECORD_DETAIL_RESET: "HIRA_RECORD_DETAIL/reset",

  ADD_HIRA_RECORD_FETCH: "ADD_HIRA_RECORD/fetch",
  ADD_HIRA_RECORD_SUCCESS: "ADD_HIRA_RECORD/success",
  ADD_HIRA_RECORD_ERROR: "ADD_HIRA_RECORD/error",

  UPDATE_HIRA_RECORD_FETCH: "UPDATE_HIRA_RECORD/fetch",
  UPDATE_HIRA_RECORD_SUCCESS: "UPDATE_HIRA_RECORD/success",
  UPDATE_HIRA_RECORD_ERROR: "UPDATE_HIRA_RECORD/error",

  ERA_LIKELIHOODS_FETCH: "ERA_LIKELIHOODS/fetch",
  ERA_LIKELIHOODS_DATA: "ERA_LIKELIHOODS/data",
  ERA_LIKELIHOODS_ERROR: "ERA_LIKELIHOODS/error",
  ERA_LIKELIHOODS_RESET: "ERA_LIKELIHOODS/reset",

  ERA_CONSEQUENCES_FETCH: "ERA_CONSEQUENCES/fetch",
  ERA_CONSEQUENCES_DATA: "ERA_CONSEQUENCES/data",
  ERA_CONSEQUENCES_ERROR: "ERA_CONSEQUENCES/error",
  ERA_CONSEQUENCES_RESET: "ERA_CONSEQUENCES/reset",

  ERA_ACTIONS_FETCH: "ERA_ACTIONS/fetch",
  ERA_ACTIONS_DATA: "ERA_ACTIONS/data",
  ERA_ACTIONS_ERROR: "ERA_ACTIONS/error",
  ERA_ACTIONS_RESET: "ERA_ACTIONS/reset",

  ERA_STATUSES_FETCH: "ERA_STATUSES/fetch",
  ERA_STATUSES_DATA: "ERA_STATUSES/data",
  ERA_STATUSES_ERROR: "ERA_STATUSES/error",
  ERA_STATUSES_RESET: "ERA_STATUSES/reset",

  ERA_ASSESSMENTS_FETCH: "ERA_ASSESSMENTS/fetch",
  ERA_ASSESSMENTS_DATA: "ERA_ASSESSMENTS/data",
  ERA_ASSESSMENTS_ERROR: "ERA_ASSESSMENTS/error",
  ERA_ASSESSMENTS_RESET: "ERA_ASSESSMENTS/reset",

  ERA_ASSESSMENT_DETAIL_FETCH: "ERA_ASSESSMENT_DETAIL/fetch",
  ERA_ASSESSMENT_DETAIL_DATA: "ERA_ASSESSMENT_DETAIL/data",
  ERA_ASSESSMENT_DETAIL_ERROR: "ERA_ASSESSMENT_DETAIL/error",
  ERA_ASSESSMENT_DETAIL_RESET: "ERA_ASSESSMENT_DETAIL/reset",

  ADD_ERA_ASSESSMENT_FETCH: "ADD_ERA_ASSESSMENT/fetch",
  ADD_ERA_ASSESSMENT_SUCCESS: "ADD_ERA_ASSESSMENT/success",
  ADD_ERA_ASSESSMENT_ERROR: "ADD_ERA_ASSESSMENT/error",

  UPDATE_ERA_ASSESSMENT_FETCH: "UPDATE_ERA_ASSESSMENT/fetch",
  UPDATE_ERA_ASSESSMENT_SUCCESS: "UPDATE_ERA_ASSESSMENT/success",
  UPDATE_ERA_ASSESSMENT_ERROR: "UPDATE_ERA_ASSESSMENT/error",

  LEGAL_REGISTER_RECORDS_FETCH: "LEGAL_REGISTER_RECORDS/fetch",
  LEGAL_REGISTER_RECORDS_DATA: "LEGAL_REGISTER_RECORDS/data",
  LEGAL_REGISTER_RECORDS_ERROR: "LEGAL_REGISTER_RECORDS/error",
  LEGAL_REGISTER_RECORDS_RESET: "LEGAL_REGISTER_RECORDS/reset",

  LEGAL_REGISTER_RECORD_DETAIL_FETCH: "LEGAL_REGISTER_RECORD_DETAIL/fetch",
  LEGAL_REGISTER_RECORD_DETAIL_DATA: "LEGAL_REGISTER_RECORD_DETAIL/data",
  LEGAL_REGISTER_RECORD_DETAIL_ERROR: "LEGAL_REGISTER_RECORD_DETAIL/error",
  LEGAL_REGISTER_RECORD_DETAIL_RESET: "LEGAL_REGISTER_RECORD_DETAIL/reset",

  ADD_LEGAL_REGISTER_RECORD_FETCH: "ADD_LEGAL_REGISTER_RECORD/fetch",
  ADD_LEGAL_REGISTER_RECORD_SUCCESS: "ADD_LEGAL_REGISTER_RECORD/success",
  ADD_LEGAL_REGISTER_RECORD_ERROR: "ADD_LEGAL_REGISTER_RECORD/error",

  UPDATE_LEGAL_REGISTER_RECORD_FETCH: "UPDATE_LEGAL_REGISTER_RECORD/fetch",
  UPDATE_LEGAL_REGISTER_RECORD_SUCCESS: "UPDATE_LEGAL_REGISTER_RECORD/success",
  UPDATE_LEGAL_REGISTER_RECORD_ERROR: "UPDATE_LEGAL_REGISTER_RECORD/error",

  /**
   * COHSS Types
   */

  COSHH_RISK_PERSONS_FETCH: "COSHH_RISK_PERSONS/fetch",
  COSHH_RISK_PERSONS_DATA: "COSHH_RISK_PERSONS/data",
  COSHH_RISK_PERSONS_ERROR: "COSHH_RISK_PERSONS/error",

  COSHH_CLASSIFICATIONS_FETCH: "COSHH_CLASSIFICATIONS/fetch",
  COSHH_CLASSIFICATIONS_DATA: "COSHH_CLASSIFICATIONS/data",
  COSHH_CLASSIFICATIONS_ERROR: "COSHH_CLASSIFICATIONS/error",

  COSHH_HAZARD_TYPES_FETCH: "COSHH_HAZARD_TYPES/fetch",
  COSHH_HAZARD_TYPES_DATA: "COSHH_HAZARD_TYPES/data",
  COSHH_HAZARD_TYPES_ERROR: "COSHH_HAZARD_TYPES/error",

  COSHH_EXPOSURE_ROUTES_FETCH: "COSHH_EXPOSURE_ROUTES/fetch",
  COSHH_EXPOSURE_ROUTES_DATA: "COSHH_EXPOSURE_ROUTES/data",
  COSHH_EXPOSURE_ROUTES_ERROR: "COSHH_EXPOSURE_ROUTES/error",

  COSHH_PROTECTIVE_EQUIPMENTS_FETCH: "COSHH_PROTECTIVE_EQUIPMENTS/fetch",
  COSHH_PROTECTIVE_EQUIPMENTS_DATA: "COSHH_PROTECTIVE_EQUIPMENTS/data",
  COSHH_PROTECTIVE_EQUIPMENTS_ERROR: "COSHH_PROTECTIVE_EQUIPMENTS/error",

  COSHH_SUBSTANCES_DISPOSAL_TYPES_FETCH:
    "COSHH_SUBSTANCES_DISPOSAL_TYPES/fetch",
  COSHH_SUBSTANCES_DISPOSAL_TYPES_DATA: "COSHH_SUBSTANCES_DISPOSAL_TYPES/data",
  COSHH_SUBSTANCES_DISPOSAL_TYPES_ERROR:
    "COSHH_SUBSTANCES_DISPOSAL_TYPES/error",

  COSHH_RISK_RATINGS_FETCH: "COSHH_RISK_RATINGS/fetch",
  COSHH_RISK_RATINGS_DATA: "COSHH_RISK_RATINGS/data",
  COSHH_RISK_RATINGS_ERROR: "COSHH_RISK_RATINGS/error",

  COSHH_ASSESSMENTS_FETCH: "COSHH_ASSESSMENTS/fetch",
  COSHH_ASSESSMENTS_DATA: "COSHH_ASSESSMENTS/data",
  COSHH_ASSESSMENTS_ERROR: "COSHH_ASSESSMENTS/error",

  COSHH_ASSESSMENT_DETAIL_FETCH: "COSHH_ASSESSMENT_DETAIL/fetch",
  COSHH_ASSESSMENT_DETAIL_DATA: "COSHH_ASSESSMENT_DETAIL/data",
  COSHH_ASSESSMENT_DETAIL_ERROR: "COSHH_ASSESSMENT_DETAIL/error",
  COSHH_ASSESSMENT_DETAIL_RESET: "COSHH_ASSESSMENT_DETAIL/reset",

  ADD_COSHH_ASSESSMENT_FETCH: "ADD_COSHH_ASSESSMENT/fetch",
  ADD_COSHH_ASSESSMENT_SUCCESS: "ADD_COSHH_ASSESSMENT/success",
  ADD_COSHH_ASSESSMENT_ERROR: "ADD_COSHH_ASSESSMENT/error",

  UPDATE_COSHH_ASSESSMENT_FETCH: "UPDATE_COSHH_ASSESSMENT/fetch",
  UPDATE_COSHH_ASSESSMENT_SUCCESS: "UPDATE_COSHH_ASSESSMENT/success",
  UPDATE_COSHH_ASSESSMENT_ERROR: "UPDATE_COSHH_ASSESSMENT/error",

  /**
   * COHSS Types End
   */
};
export default types;
